name: flutter_app_sportly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  go_router: ^6.0.9
  flutter_riverpod: ^2.2.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.7
  card_swiper: ^2.0.4
  shimmer: ^2.0.0
  intl: ^0.18.0
  dio: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/


